### ISSUE TITLE
Still working on 2nd edition?

### ISSUE THREAD

**Issue by januz** [ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse_2_ed#1]
Thanks for all your work on "Statistical Rethinking with brms, ggplot2, and the tidyverse"! I started reading the book and was happy to find your project. I am reading the second edition of the book and your project for the 1st edition is still very useful as (at least in the first chapters) there seems to be a lot of overlap. I wondered whether you were working on a version for the 2nd edition of the book and found this repository. Are you still planning to release this? Thanks so much!

**Comment by ASKurz** [comment]
Hey @januz, thanks for your interest. I'm glad you found my translation of the first edition helpful. 

Yes, I still plan on working on a translation of the 2nd edition. However, it's low on my to-do list and won't likely come out any time soon. Not in a finished form, at least. Perhaps I'll release partial **bookdown** versions every once in a while, as I complete the translations of individual chapters. Any movements along those lines will be announced on [twitter](https://twitter.com/SolomonKurz).

**Comment by januz** [comment]
Great, thank you!!
