### ISSUE TITLE
sample_n() has been superseded

### ISSUE THREAD

**Issue by rpruim** [ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse_2_ed#14]
From the help:

> sample_n() and sample_frac() have been superseded in favour of slice_sample(). While they will not be deprecated in the near future, retirement means that we will only perform critical bug fixes, so we recommend moving to the newer alternative.

No harm (at least for now) in sticking with `sample_n()`, and the name is nicer, but Hadley's preference is that folks migrate to `slice_sample()`.

**Comment by ASKurz** [comment]
Good to know. I'll make the switch in the next release.
