### ISSUE TITLE
An attempt to reproduce Figure 9.3

### ISSUE THREAD

**Issue by jameshenegan** [ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse_2_ed#21]
Hello Solomon, I have been enjoying your work!

Responding to the first paragraph of [Section 9.2.2](https://bookdown.org/content/4857/markov-chain-monte-carlo.html#high-dimensional-problems.), I am providing a link to my attempt to reproduce Figure 9.3 [here](https://gist.github.com/jameshenegan/2048c8cb19f54b917e4fcd740a7031b9).

One thing I want to point out:  in the text, McElreath says that the step size for the plot on the left is 0.01.  However, the figure indicates that the step size is 0.1.  I think the figure is correct.

**Comment by ASKurz** [comment]
Hey @jameshenegan, this is excellent. Thanks for sharing! I will include this work and credit you for it in the next update of the book.

**Comment by ASKurz** [comment]
After playing around with your solution, for a bit, it looks like `breaks = 9^(-(10 * 1:25))` works a little better for the contour lines.

**Comment by ASKurz** [comment]
You can preview my implementation [here](https://github.com/ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse_2_ed/blob/master/in_the_works/9.2.2.md).
