### ISSUE TITLE
cross link ebook editions

### ISSUE THREAD

**Issue by wpetry** [ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse_2_ed#24]
I always seem to have a hard time finding the 2nd edition directly from a search engine. I suppose this is mostly user error on my part & I ought to just bookmark the page already. But the problem suggests that new users might also have difficulty finding the edition they want. Would you consider adding a link to the other edition right at the top to help folks immediately identify when they've stumbled onto the wrong version? Something like:
![Screenshot 2021-02-11 at 9 35 18](https://user-images.githubusercontent.com/11151477/107651078-1d03c500-6c4d-11eb-92df-22c3b19b9171.png)
and
![Screenshot 2021-02-11 at 9 44 42](https://user-images.githubusercontent.com/11151477/107651837-f5f9c300-6c4d-11eb-8a23-7a1dd98764db.png)

Kudos for putting together these lovely resources.

**Comment by ASKurz** [comment]
I'm not in love with the implementation, but your point is well taken. Thanks for bringing it to my attention (and for the kind words). I'll chew on this.

**Comment by wpetry** [comment]
> I'm not in love with the implementation
Me neither. Just trying to capture the essential features: near the top, quick to spot, brief to read+click/ignore

**Comment by ASKurz** [comment]
There’s a related issue that your first example highlights. There are links to old outdated versions of some of my ebooks floating around. For example, my translation of McElreath’s first edition is now on version 1.2.0. Many of these pesky older links are connected to a university email I no longer have access to. @wpetry, I definitely don’t expect you to come up with a solution to this. But if anyone else knows how to remove **bookdown** books connected to old emails one no longer has access to, I’d love to hear about it.
