### ISSUE TITLE
Consider using facet labellers?

### ISSUE THREAD

**Issue by rpruim** [ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse_2_ed#29]
Instead of using `str_c()` to modify the data, facet labelling can be used to include the variable name and value in facet labels.  See https://ggplot2.tidyverse.org/reference/labellers.html for examples.

**Comment by ASKurz** [comment]
Good suggestion. I've been using `labeller = label_both` more, lately. But I suspect that hasn't made it into my books.
