### ISSUE TITLE
Chapter 10.1.1: plot of shape and entropy

### ISSUE THREAD

**Issue by hamedbh** [ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse_2_ed#39]
I think the issue with the slope looking different to that in the book is because you're computing entropy with a grid approximation. When I used the exact formula for the entropy of the generalised normal distribution (also on the Wikipedia page) I got something that looked much more like the book. Here's my code (my styling is slightly different to yours as I'm sticking more closely to the book's look, although I like the Studio Ghibli palette): 

```
tibble(beta = seq(1, 4, length.out = 100)) %>% 
  mutate(alpha = solve_for_alpha(beta)) %>% 
  mutate(entropy = (1 / beta) - log((beta) / (2 * alpha * gamma(1 / beta)))) %>% 
  ggplot(aes(beta, entropy)) + 
  geom_line(colour = "steelblue") + 
  geom_vline(xintercept = 2, linetype = 2, colour = "grey50") + 
  scale_x_continuous("shape", breaks = seq(1, 5, by = 0.5))
```

I only noticed the difference because I was originally computing entropy on a grid as well, but a much finer one. When I got much higher values for the entropy than the book it got me digging around to figure out why. 
![image](https://user-images.githubusercontent.com/1893892/164188161-8217c1f0-7fc3-47a7-bd7b-efc270bd9d54.png)

**Comment by ASKurz** [comment]
You're right, that's the solution. Thanks!

**Comment by hamedbh** [comment]
It’s Hamed Bastan-Hagh.
