### ISSUE TITLE
Quarto port and content update for 2023 lectures + beginning of 3rd edition

### ISSUE THREAD

**Issue by JamesHWade** [ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse_2_ed#43]
With the start of the 2023 flavor of the course, I've started porting the book over to quarto [in a fork](https://github.com/JamesHWade/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse_2_ed). I see that the contributing guide asks for that sort of thing to be mentioned here over pull requests. I'm more than happy to PR my changes, but I completely understand if you'd prefer I didn't.

One of the biggest benefits of the quarto port and [publishing with Quarto Pubs](https://jameshwade.quarto.pub/statistical-rethinking-with-brms-ggplot2-and-the-tidyverse-second-edition/) is a major reduction in the repo size since the `_book` folder is no longer needs to be kept around.

Happy to hear your thoughts on how / if you'd like to collaborate on this.

**Comment by ASKurz** [comment]
Hey @JamesHWade, I don't plan on switching to Quarto anytime soon, but thanks for the heads up!
