### ISSUE TITLE
Section 4.4.3.4. Predictions for E{height} at a given weight

### ISSUE THREAD

**Issue by dipetkov** [ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse_2_ed#44]
In this code snippet:
``` r
mu_at_50 <- 
  post %>% 
  transmute(mu_at_50 = b_Intercept + b_weight_c + 5.01)
```
Is the formula for `mu_at_50` correct?

Or should we compute it as `mu_at_50 = b_Intercept + b_weight_c * 5.01`?

**Comment by ASKurz** [comment]
Good catch! Yeah, I think `mu_at_50 = b_Intercept + b_weight_c * 5.01` is the way to go.

**Comment by ASKurz** [comment]
@dipetkov, I'll close this issue after I've made this correction in the next version of the ebook.
