### ISSUE TITLE
Use of 'package' argument in data()

### ISSUE THREAD

**Issue by ecmerkle** [ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse_2_ed#9]
Thanks for the nice resource to supplement Statistical Rethinking. I had one suggestion for loading datasets from the rethinking package. Instead of going to the trouble of detaching rethinking after pulling out a dataset, you might be able to do something like:

`data(UCBadmit, package="rethinking")`

I believe that rethinking is not loaded in that case, but you still get the dataset. It might streamline some future code, though it is probably not worth changing the existing code. (so feel free to close this issue immediately)

**Comment by ASKurz** [comment]
Ooo, that works nice. I'll make the change in the upcoming update. Thanks!
